/*
 * Presets.hpp
 *
 * Definitions for cross-platform built-in factory presets.
 * Here are just two dummy presets, but the framework is
 * complete and could be properly employed with the
 * necessary data.
 *
 *  Created on: 1 Aug 2010
 *      Author: Jonathan Crooke (jc9873@bris.ac.uk)
 */

#ifndef PRESETS_HPP_
#define PRESETS_HPP_

#include "ParamTypes.hpp"
#include "Strings.hpp"

namespace hotpants {

  const kPreset kFactoryPresets[kNumOfPresets] = {
    { kPreset_Factory1, kPresetName_Factory1, {
      { kParam_AmpAttack,     0.1 },
      { kParam_AmpDecay,      0.5 },
      { kParam_AmpSustain,    75 },
      { kParam_AmpRelease,    0.25 },
      { kParam_AmpScaling,    50 },
      { kParam_Velocity,      0.0 },
      { kParam_Osc1Wave,      kWave_SquareFixed },
      { kParam_Osc1Tuning,    0.0 },
      { kParam_Osc1Amp,       1.0 },
      { kParam_Osc2Wave,      kWave_SineDirect },
      { kParam_Osc2Tuning,    0.0 },
      { kParam_Osc2Fine,      0.0 },
      { kParam_OscMod,        kOscMod_None },
      { kParam_Osc2Amp,       0.0 },
      { kParam_Osc3Wave,      kWave_SineDirect },
      { kParam_Osc3Tuning,    0.0 },
      { kParam_Osc3Amp,       0.0 },
      { kParam_OscAnalogue,   0.0 },
      { kParam_PulseWidth,    50 },
      { kParam_Filt1Type,     kFiltType_Off },
      { kParam_Filt1Cutoff,   5000 },
      { kParam_Filt1Q,        0.7 },
      { kParam_Filt1EQGain,   -3 },
      { kParam_Filt2Type,     kFiltType_Off },
      { kParam_Filt2Cutoff,   5000 },
      { kParam_Filt2Q,        0.7 },
      { kParam_Filt2EQGain,   -3 },
      { kParam_FiltConnect,   kConnect_Serial },
      { kParam_FiltMix,       0.5 },
      { kParam_FiltKeyTrack,  100 },
      { kParam_LFO1Target,    eModT_GlobalTuning },
      { kParam_LFO1Wave,      kWave_SineDirect },
      { kParam_LFO1Rate,      9.621 },
      { kParam_LFO1Amount,    3.3 },
      { kParam_LFO2Target,    eModT_None },
      { kParam_LFO2Wave,      kWave_SineDirect },
      { kParam_LFO2Rate,      2.0 },
      { kParam_LFO2Amount,    0.6 },
      { kParam_Env1Target,    eModT_None },
      { kParam_Env1Amount,    0.0 },
      { kParam_Env1Attack,    0.1 },
      { kParam_Env1Decay,     0.5 },
      { kParam_Env1Sustain,   75 },
      { kParam_Env1Release,   0.25 },
      { kParam_Env2Target,    eModT_None },
      { kParam_Env2Amount,    0.0 },
      { kParam_Env2Attack,    0.1 },
      { kParam_Env2Decay,     0.5 },
      { kParam_WheelTarget,   eModT_None },
      { kParam_WheelAmount,   50 },
      { kParam_VeloTarget,    eModT_None },
      { kParam_VeloAmount,    50 },
      { kParam_DistortType,   kDistortion_Off },
      { kParam_DistortGain,   0.0 },
      { kParam_DelayL_Mix,    44.6 },
      { kParam_DelayL_Time,   0.138 },
      { kParam_DelayL_FB,     36 },
      { kParam_DelayR_Mix,    44.6 },
      { kParam_DelayR_Time,   0.084 },
      { kParam_DelayR_FB,     56.8 },
      { kParam_DelayHP,       571.7 },
      { kParam_DelayLP,       11065 },
      { kParam_Polyphony,     36 },
      { kParam_Portamento,    0.1 },
      { kParam_PitchBend,     2.0 },
      { kParam_GlobalTuning,  0.0 },
      { kParam_GlobalVolume,  1.0 }}},
    { kPreset_Factory2, kPresetName_Factory2, {
      { kParam_AmpAttack,     0.1 },
      { kParam_AmpDecay,      0.5 },
      { kParam_AmpSustain,    75 },
      { kParam_AmpRelease,    0.25 },
      { kParam_AmpScaling,    50 },
      { kParam_Velocity,      0.0 },
      { kParam_Osc1Wave,      kWave_SquareFixed },
      { kParam_Osc1Tuning,    0.0 },
      { kParam_Osc1Amp,       1.0 },
      { kParam_Osc2Wave,      kWave_SineDirect },
      { kParam_Osc2Tuning,    0.0 },
      { kParam_Osc2Fine,      0.0 },
      { kParam_OscMod,        kOscMod_None },
      { kParam_Osc2Amp,       0.0 },
      { kParam_Osc3Wave,      kWave_SineDirect },
      { kParam_Osc3Tuning,    0.0 },
      { kParam_Osc3Amp,       0.0 },
      { kParam_OscAnalogue,   0.0 },
      { kParam_PulseWidth,    50 },
      { kParam_Filt1Type,     kFiltType_Off },
      { kParam_Filt1Cutoff,   5000 },
      { kParam_Filt1Q,        0.7 },
      { kParam_Filt1EQGain,   -3 },
      { kParam_Filt2Type,     kFiltType_Off },
      { kParam_Filt2Cutoff,   5000 },
      { kParam_Filt2Q,        0.7 },
      { kParam_Filt2EQGain,   -3 },
      { kParam_FiltConnect,   kConnect_Serial },
      { kParam_FiltMix,       0.5 },
      { kParam_FiltKeyTrack,  100 },
      { kParam_LFO1Target,    eModT_GlobalTuning },
      { kParam_LFO1Wave,      kWave_SineDirect },
      { kParam_LFO1Rate,      9.621 },
      { kParam_LFO1Amount,    3.3 },
      { kParam_LFO2Target,    eModT_None },
      { kParam_LFO2Wave,      kWave_SineDirect },
      { kParam_LFO2Rate,      2.0 },
      { kParam_LFO2Amount,    0.6 },
      { kParam_Env1Target,    eModT_None },
      { kParam_Env1Amount,    0.0 },
      { kParam_Env1Attack,    0.1 },
      { kParam_Env1Decay,     0.5 },
      { kParam_Env1Sustain,   75 },
      { kParam_Env1Release,   0.25 },
      { kParam_Env2Target,    eModT_None },
      { kParam_Env2Amount,    0.0 },
      { kParam_Env2Attack,    0.1 },
      { kParam_Env2Decay,     0.5 },
      { kParam_WheelTarget,   eModT_None },
      { kParam_WheelAmount,   50 },
      { kParam_VeloTarget,    eModT_None },
      { kParam_VeloAmount,    50 },
      { kParam_DistortType,   kDistortion_Off },
      { kParam_DistortGain,   0.0 },
      { kParam_DelayL_Mix,    44.6 },
      { kParam_DelayL_Time,   0.138 },
      { kParam_DelayL_FB,     36 },
      { kParam_DelayR_Mix,    44.6 },
      { kParam_DelayR_Time,   0.084 },
      { kParam_DelayR_FB,     56.8 },
      { kParam_DelayHP,       571.7 },
      { kParam_DelayLP,       11065 },
      { kParam_Polyphony,     36 },
      { kParam_Portamento,    0.1 },
      { kParam_PitchBend,     2.0 },
      { kParam_GlobalTuning,  0.0 },
      { kParam_GlobalVolume,  1.0 }}}
  };

}
#endif /* PRESETS_HPP_ */
